inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*_spec.rb'
    - 'lib/ego/options.rb'
    - 'lib/ego/plugins/*.rb'

Style/Semicolon:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/SingleLineMethods:
  Exclude:
    - 'spec/**/*_spec.rb'

